name: orders-tests

on:
  pull_request:
    paths: 
      - 'orders/**'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Tests
        run: | 
          cd orders
          npm i
          npm run test:ci
