name: tickets-tests

on:
  pull_request:
    paths: 
      - 'tickets/**'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Tests
        run: | 
          cd tickets
          npm i
          npm run test:ci
